name: 将 Release 同步到 Xposed Repo

on:
  release:
    types: [published]
  workflow_dispatch:


jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 从当前仓库下载 APK
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          file: ".*\\.apk"
          regex: true
          target: "./"

      - name: 发布到 Xposed-Modules-Repo
        uses: softprops/action-gh-release@v2
        with:
          repository: "Xposed-Modules-Repo/io.github.xjyzs.systemednotificationblocker"
          token: ${{ secrets.XPOSED_REPO_TOKEN }}
          tag_name: ${{ github.event.release.tag_name }}
          name: ${{ github.event.release.name }}
          body: ${{ github.event.release.body }}
          files: "*.apk"